name=ATD5-P4
version=1.0.0
author=ArtronShop CO.,LTD.
maintainer=Sonthaya Nongnuch <sonthaya.nt@hotmail.com>
sentence=Library for ATD5-P4
paragraph=HMI with ESP32-P4
category=Display
url=https://github.com/ArtronShop/ATD5-P4_Library
architectures=esp32
